# Generated by Django 6.1.1 on 2026-09-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('WEATHER', 'Weather'), ('SPORTS', 'Sports'), ('POLITICS', 'Politics'), ('ECONOMICS', 'Economics'), ('TECHNOLOGY', 'Technology'), ('GENERAL', 'General')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('resolution_source', models.URLField(blank=True, help_text='Source used to verify the real-world outcome.')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='winning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_events', to='events.outcome'),
        ),
    ]
